### ISSUE TITLE
How can i pass --from-addr in invoke_contract method.

### ISSUE THREAD

**Issue by Np23295** [CityOfZion/neo-python-rpc#11]
I am trying to pass --from-addr in invoke_contract method but its returning invalid args. How can i pass owner address into it?

**Comment by ixje** [comment]
while old question, I'm just going to answer it for whomever passes by:
the `invoke` RPC method does not support providing a `--from-addr`
see: https://docs.neo.org/en-us/node/cli/latest-version/api/invoke.html
