### ISSUE TITLE
Could not call method getblockcount with endpoint. Connection to 52.14.184.44 t imed out. (connect timeout=10)'))

### ISSUE THREAD

**Issue by plgonzalezrx8** [CityOfZion/neo-python-rpc#5]
Could not call method getblockcount with endpoint: http://52.14.184.44:8880 : HTTPConnectionPoo
l(host='52.14.184.44', port=8880): Max retries exceeded with url: / (Caused by ConnectTimeoutEr
ror(<urllib3.connection.HTTPConnection object at 0x7f9ae1461828>, 'Connection to 52.14.184.44 t
imed out. (connect timeout=10)'))

**Comment by metachris** [comment]
Fixed with new release.

**Comment by plgonzalezrx8** [comment]
This  issue has been fix, update your local repo.
